name: Build App & Deploy

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: production
      image_name: paas-deploy
    secrets:
      CAPROVER_SERVER: ${{ secrets.CAPROVER_SERVER }}
      APP_NAME: ${{ secrets.APP_NAME }}
      APP_TOKEN: ${{ secrets.APP_TOKEN }}
